FROM eclipse-temurin:17-jdk-focal AS builder

 WORKDIR /app
 COPY healthcare/.mvn/ .mvn
 COPY healthcare/mvnw healthcare/pom.xml ./

 # Converting the mvnw line endings during build (if you don’t change line endings of the mvnw file)
 RUN apt-get update && apt-get install -y dos2unix
 RUN dos2unix ./mvnw

 RUN ./mvnw dependency:resolve

 COPY healthcare/src ./src

# Build the JAR
RUN ./mvnw clean install -DskipTests

FROM eclipse-temurin:17-jre-focal
WORKDIR /app

# Copy only the built JAR from the builder stage
COPY --from=builder /app/target/healthcare-0.0.1-SNAPSHOT.jar ./backend.jar

# Run the app
CMD ["java", "-jar", "./backend.jar"]
